### create a new patient eneity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "kafka Joe",
  "email": "kafka@example.com",
  "address": "3 GREEN AVE,LA 10001",
  "dateOfBirth": "1991-08-11",
  "registeredDate": "2024-02-10"
}

###